/**
 * File storage (spec section 19).
 *
 * Section 19 is specific about attachments: access-controlled, tied to a
 * complaint or visit, metadata stored, type and size validated, and **not
 * publicly accessible by default**.
 *
 * Two decisions follow from that last clause:
 *
 *  - Files live **outside** any static-served directory. Nothing is reachable
 *    by URL; every byte is served by an authenticated handler that re-checks
 *    the caller's scope against the parent complaint.
 *  - Storage keys are opaque and generated, never derived from the uploaded
 *    filename. A name like `../../.env` would otherwise escape the storage
 *    root, and a guessable key would make the access check bypassable by
 *    anyone who could construct one.
 *
 * The `StorageDriver` interface exists so `STORAGE_DRIVER=s3` is a config
 * change later rather than a data migration — nothing above this layer knows
 * where bytes actually live.
 */
import { createHash, randomUUID } from 'node:crypto';
import { createReadStream, type ReadStream } from 'node:fs';
import fs from 'node:fs/promises';
import path from 'node:path';
import { config } from '../config/env.js';
import { badRequest } from '../http/errors.js';

/* ---- Accepted types ---------------------------------------------------- */

/**
 * Allowed file types, each with the byte signature that proves it.
 *
 * The browser-supplied MIME type is a *claim*, not evidence — anything can be
 * uploaded as `image/jpeg`. Section 19 requires file type to be validated, so
 * we check the actual leading bytes instead.
 */
interface FileSignature {
  mimeType: string;
  extension: string;
  /** Bytes that must appear at `offset` for the file to be this type. */
  magic: number[];
  offset: number;
}

const SIGNATURES: readonly FileSignature[] = [
  { mimeType: 'image/jpeg', extension: 'jpg', magic: [0xff, 0xd8, 0xff], offset: 0 },
  {
    mimeType: 'image/png',
    extension: 'png',
    magic: [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a],
    offset: 0,
  },
  /* WEBP is RIFF....WEBP — the inner tag at offset 8 is what distinguishes it. */
  { mimeType: 'image/webp', extension: 'webp', magic: [0x57, 0x45, 0x42, 0x50], offset: 8 },
  /* MP4 and friends carry `ftyp` at offset 4. */
  { mimeType: 'video/mp4', extension: 'mp4', magic: [0x66, 0x74, 0x79, 0x70], offset: 4 },
];

export interface DetectedType {
  mimeType: string;
  extension: string;
}

/**
 * Identifies a file by its contents, or rejects it.
 *
 * HEIC deliberately is not accepted: iPhones produce it by default, but
 * nothing in the admin or centre portals can display it, so an accepted HEIC
 * would be an attachment nobody can look at. Phones can be asked to capture
 * JPEG instead.
 */
export function detectFileType(buffer: Buffer): DetectedType {
  for (const signature of SIGNATURES) {
    const slice = buffer.subarray(
      signature.offset,
      signature.offset + signature.magic.length,
    );

    if (slice.length !== signature.magic.length) continue;
    if (signature.magic.every((byte, i) => slice[i] === byte)) {
      return { mimeType: signature.mimeType, extension: signature.extension };
    }
  }

  throw badRequest(
    'That file type is not accepted. Upload a JPEG, PNG, WEBP image or an MP4 video.',
    [{ field: 'file', message: 'Unsupported file type' }],
  );
}

/* ---- Driver interface -------------------------------------------------- */

export interface StoredFile {
  storageKey: string;
  sizeBytes: number;
  checksum: string;
  mimeType: string;
}

export interface StorageDriver {
  save(buffer: Buffer, context: { complaintId: string; extension: string; mimeType: string }): Promise<StoredFile>;
  read(storageKey: string): Promise<ReadStream>;
  exists(storageKey: string): Promise<boolean>;
  /** Removes bytes. Only ever called to clean up a failed write. */
  remove(storageKey: string): Promise<void>;
}

/* ---- Local driver ------------------------------------------------------ */

class LocalStorageDriver implements StorageDriver {
  private readonly root: string;

  constructor(root: string) {
    this.root = path.resolve(root);
  }

  /**
   * Resolves a key to an absolute path, refusing anything that escapes.
   *
   * Keys are generated by `save`, so a traversing key should be impossible —
   * but this is the last line between a user-influenced string and the file
   * system, and the check costs nothing.
   */
  private resolve(storageKey: string): string {
    const full = path.resolve(this.root, storageKey);

    if (full !== this.root && !full.startsWith(this.root + path.sep)) {
      throw badRequest('Invalid storage key');
    }

    return full;
  }

  async save(
    buffer: Buffer,
    context: { complaintId: string; extension: string },
  ): Promise<StoredFile> {
    /* Sharded by complaint so one directory never accumulates every file in
       the system, and a filename that is a UUID rather than anything the
       uploader chose. */
    const storageKey = path.posix.join(
      'complaints',
      context.complaintId,
      `${randomUUID()}.${context.extension}`,
    );

    const destination = this.resolve(storageKey);
    await fs.mkdir(path.dirname(destination), { recursive: true });
    await fs.writeFile(destination, buffer);

    return {
      storageKey,
      sizeBytes: buffer.byteLength,
      checksum: createHash('sha256').update(buffer).digest('hex'),
      mimeType: '',
    };
  }

  async read(storageKey: string): Promise<ReadStream> {
    const source = this.resolve(storageKey);
    await fs.access(source);
    return createReadStream(source);
  }

  async exists(storageKey: string): Promise<boolean> {
    try {
      await fs.access(this.resolve(storageKey));
      return true;
    } catch {
      return false;
    }
  }

  async remove(storageKey: string): Promise<void> {
    await fs.rm(this.resolve(storageKey), { force: true });
  }
}

let driver: StorageDriver | undefined;

export function storage(): StorageDriver {
  if (!driver) {
    /* Only one driver today. The switch is here so adding S3 is a case
       rather than a refactor of every caller. */
    switch (config.STORAGE_DRIVER) {
      case 'local':
      default:
        driver = new LocalStorageDriver(config.STORAGE_LOCAL_PATH);
    }
  }

  return driver;
}

/** Test seam: lets a suite point storage somewhere disposable. */
export function setStorageDriver(replacement: StorageDriver | undefined): void {
  driver = replacement;
}

export const maxFileBytes = (): number => config.STORAGE_MAX_FILE_MB * 1024 * 1024;
