/**
 * Technicians (spec sections 3.2 and 9, "Technician management").
 *
 * Section 9: add, edit, activate/deactivate, view workload, assign and
 * reassign jobs. Assigning happens on the complaint itself; this page is the
 * people.
 *
 * ## Passwords are shown once
 *
 * A new technician, or one whose password is reset, gets a temporary password
 * generated by the server. Only its hash is stored, so the one moment it can
 * be read is right after it is issued — and the dialog says so plainly. The
 * technician must replace it the first time they sign in.
 *
 * ## Deactivation does not strand work
 *
 * Section 9: "If technician is deactivated with active jobs: existing jobs
 * remain in history. Service Center Owner must reassign active jobs." The
 * server reports those jobs as it deactivates, and they are listed straight
 * away with a link to each, rather than left for the Owner to discover.
 */
import { useMutation } from '@tanstack/react-query';
import { KeyRound, Pencil, Plus, Power, UserPlus } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { Link } from 'react-router';
import { toast } from 'sonner';
import { Badge } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';
import { Card, PageHeader } from '@/components/ui/Card';
import { Dialog } from '@/components/ui/Dialog';
import { Input } from '@/components/ui/Field';
import { EmptyState, ErrorState, Skeleton, errorMessage } from '@/components/ui/States';
import { api, ApiError } from '@/lib/api';
import { cn, formatMobile, fromNow, humanize } from '@/lib/format';
import type { IssuedPassword, User } from '@/lib/types';
import { IssuedPasswordDialog } from '@/components/records/Records';
import { useRefreshCenter, useTechnicians } from './shared';

interface StrandedJob {
  complaintId: string;
  complaintNumber: string;
  status: string;
}

export function TechniciansPage() {
  const [showInactive, setShowInactive] = useState(false);
  const technicians = useTechnicians({ includeInactive: showInactive });

  const [adding, setAdding] = useState(false);
  const [editing, setEditing] = useState<User | null>(null);
  const [toggling, setToggling] = useState<User | null>(null);
  const [resetting, setResetting] = useState<User | null>(null);
  const [issued, setIssued] = useState<IssuedPassword | null>(null);
  const [stranded, setStranded] = useState<{ name: string; jobs: StrandedJob[] } | null>(null);

  const rows = technicians.data?.items ?? [];

  return (
    <>
      <PageHeader
        title="Technicians"
        description={
          technicians.data
            ? `${rows.length} ${showInactive ? '' : 'active '}${rows.length === 1 ? 'technician' : 'technicians'}`
            : undefined
        }
        actions={
          <Button icon={<Plus className="size-4" />} onClick={() => setAdding(true)}>
            Add technician
          </Button>
        }
      />

      <label className="mb-4 inline-flex cursor-pointer items-center gap-2 text-sm text-slate-700">
        <input
          type="checkbox"
          checked={showInactive}
          onChange={(event) => setShowInactive(event.target.checked)}
          className="size-4 rounded accent-brand-700"
        />
        Show deactivated technicians
      </label>

      <Card className="overflow-hidden">
        {technicians.error && !technicians.data ? (
          <ErrorState error={technicians.error} onRetry={() => void technicians.refetch()} />
        ) : !technicians.data ? (
          <div className="divide-y divide-slate-100" aria-busy aria-label="Loading technicians">
            {Array.from({ length: 4 }, (_, i) => (
              <div key={i} className="flex items-center gap-4 px-5 py-4">
                <Skeleton className="h-4 w-40" />
                <Skeleton className="h-4 flex-1" />
                <Skeleton className="h-8 w-24" />
              </div>
            ))}
          </div>
        ) : rows.length === 0 ? (
          <EmptyState
            icon={<UserPlus className="size-5" />}
            title="No technicians yet"
            description="Add your first technician. They sign in with their mobile number and a password you give them."
            action={
              <Button size="sm" icon={<Plus className="size-3.5" />} onClick={() => setAdding(true)}>
                Add technician
              </Button>
            }
          />
        ) : (
          /* `relative`, so the screen-reader-only "Actions" label is clipped by
             this scroll box instead of widening the whole page. */
          <div className="relative overflow-x-auto">
            <table className="w-full min-w-[880px] text-left text-sm">
              <thead className="whitespace-nowrap border-b border-slate-200 bg-slate-50/70 text-xs font-medium uppercase tracking-wide text-slate-500">
                <tr>
                  <th scope="col" className="px-5 py-3">Technician</th>
                  <th scope="col" className="px-5 py-3">Mobile</th>
                  <th scope="col" className="px-5 py-3 text-right">Open jobs</th>
                  <th scope="col" className="px-5 py-3 text-right">Visits today</th>
                  <th scope="col" className="px-5 py-3">Status</th>
                  <th scope="col" className="px-5 py-3">Last sign-in</th>
                  <th scope="col" className="px-5 py-3 text-right">
                    <span className="sr-only">Actions</span>
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {rows.map((technician) => (
                  <tr key={technician.id} className={cn(!technician.isActive && 'bg-slate-50/60')}>
                    <td className="whitespace-nowrap px-5 py-3.5">
                      <p className={cn('font-medium', technician.isActive ? 'text-slate-900' : 'text-slate-500')}>
                        {technician.name}
                      </p>
                      {technician.email && <p className="mt-0.5 text-xs text-slate-500">{technician.email}</p>}
                    </td>
                    <td className="tabular whitespace-nowrap px-5 py-3.5 text-slate-700">
                      <a href={`tel:+91${technician.mobile}`} className="hover:text-brand-700 hover:underline">
                        {formatMobile(technician.mobile)}
                      </a>
                    </td>
                    <td className="tabular px-5 py-3.5 text-right">
                      {(technician.workload?.openJobs ?? 0) > 0 ? (
                        <Link
                          to={`/center/complaints?technicianId=${technician.id}&open=true`}
                          className="font-medium text-slate-900 hover:text-brand-700 hover:underline"
                        >
                          {technician.workload?.openJobs}
                        </Link>
                      ) : (
                        <span className="text-slate-400">0</span>
                      )}
                    </td>
                    <td className="tabular px-5 py-3.5 text-right text-slate-700">
                      {technician.workload?.visitsToday ?? 0}
                    </td>
                    <td className="px-5 py-3.5">
                      <div className="flex flex-wrap gap-1.5">
                        {technician.isActive ? (
                          <Badge className="bg-emerald-50 text-emerald-700 ring-emerald-600/20">Active</Badge>
                        ) : (
                          <Badge className="bg-slate-100 text-slate-600 ring-slate-500/20">Deactivated</Badge>
                        )}
                        {technician.isActive && technician.mustChangePassword && (
                          <Badge className="bg-amber-50 text-amber-800 ring-amber-600/25">
                            {/* A password reset sets this flag on someone who has
                                signed in plenty of times before — "not signed in
                                yet" next to a real last-sign-in time said otherwise. */}
                            {technician.lastLoginAt ? 'Must set a new password' : 'Not signed in yet'}
                          </Badge>
                        )}
                      </div>
                    </td>
                    <td className="whitespace-nowrap px-5 py-3.5 text-slate-500">
                      {technician.lastLoginAt ? fromNow(technician.lastLoginAt) : 'Never'}
                    </td>
                    <td className="px-5 py-3.5">
                      <div className="flex justify-end gap-1">
                        <Button
                          size="sm"
                          variant="ghost"
                          icon={<Pencil className="size-3.5" />}
                          onClick={() => setEditing(technician)}
                        >
                          Edit
                        </Button>
                        {technician.isActive && (
                          <Button
                            size="sm"
                            variant="ghost"
                            icon={<KeyRound className="size-3.5" />}
                            onClick={() => setResetting(technician)}
                          >
                            Reset password
                          </Button>
                        )}
                        <Button
                          size="sm"
                          variant="ghost"
                          icon={<Power className="size-3.5" />}
                          className={technician.isActive ? 'text-red-600 hover:bg-red-50 hover:text-red-700' : ''}
                          onClick={() => setToggling(technician)}
                        >
                          {technician.isActive ? 'Deactivate' : 'Activate'}
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Card>

      <AddTechnicianDialog open={adding} onClose={() => setAdding(false)} onCreated={setIssued} />

      {editing && <EditTechnicianDialog technician={editing} onClose={() => setEditing(null)} />}

      {toggling && (
        <ToggleActiveDialog
          technician={toggling}
          onClose={() => setToggling(null)}
          onStranded={(jobs) => setStranded({ name: toggling.name, jobs })}
        />
      )}

      {resetting && (
        <ResetPasswordDialog technician={resetting} onClose={() => setResetting(null)} onIssued={setIssued} />
      )}

      {issued && <IssuedPasswordDialog issued={issued} onClose={() => setIssued(null)} />}

      {stranded && (
        <Dialog
          open
          onClose={() => setStranded(null)}
          size="sm"
          title="Reassign these jobs"
          description={`${stranded.name} is deactivated, but still has ${stranded.jobs.length} open ${
            stranded.jobs.length === 1 ? 'job' : 'jobs'
          }. Their history stays; the live work needs a new technician.`}
          footer={<Button onClick={() => setStranded(null)}>Done</Button>}
        >
          <ul className="divide-y divide-slate-100 rounded-lg border border-slate-200">
            {stranded.jobs.map((job) => (
              <li key={job.complaintId} className="flex items-center justify-between gap-3 px-3 py-2.5">
                <span className="text-sm">
                  <span className="tabular font-medium text-slate-900">{job.complaintNumber}</span>
                  <span className="ml-2 text-xs text-slate-500">{humanize(job.status)}</span>
                </span>
                <Link
                  to={`/center/complaints/${job.complaintId}`}
                  className="text-sm font-medium text-brand-700 hover:underline"
                >
                  Reassign
                </Link>
              </li>
            ))}
          </ul>
        </Dialog>
      )}
    </>
  );
}

/* ---- Add --------------------------------------------------------------- */

const MOBILE = /^[6-9]\d{9}$/;

function AddTechnicianDialog({
  open,
  onClose,
  onCreated,
}: {
  open: boolean;
  onClose: () => void;
  onCreated: (issued: IssuedPassword) => void;
}) {
  const refresh = useRefreshCenter();
  const [name, setName] = useState('');
  const [mobile, setMobile] = useState('');
  const [email, setEmail] = useState('');
  const [errors, setErrors] = useState<Record<string, string>>({});

  const reset = () => {
    setName('');
    setMobile('');
    setEmail('');
    setErrors({});
  };

  const create = useMutation({
    mutationFn: () =>
      api<IssuedPassword>('/users', {
        method: 'POST',
        body: {
          role: 'TECHNICIAN',
          name: name.trim(),
          mobile: mobile.replace(/\D/g, ''),
          ...(email.trim() ? { email: email.trim() } : {}),
        },
      }),
    onSuccess: async (result) => {
      reset();
      onClose();
      onCreated(result);
      await refresh();
    },
    onError: (error) => {
      if (error instanceof ApiError && error.issues.length > 0) {
        setErrors(Object.fromEntries(error.issues.map((issue) => [issue.field, issue.message])));
      } else if (error instanceof ApiError && error.status === 409) {
        setErrors({ mobile: error.message });
      } else {
        toast.error(errorMessage(error));
      }
    },
  });

  const submit = (event: FormEvent) => {
    event.preventDefault();
    const found: Record<string, string> = {};
    if (!name.trim()) found['name'] = 'Enter the technician’s name';
    if (!MOBILE.test(mobile.replace(/\D/g, ''))) found['mobile'] = 'Enter a valid 10-digit mobile number';
    setErrors(found);
    if (Object.keys(found).length === 0) create.mutate();
  };

  return (
    <Dialog
      open={open}
      onClose={() => {
        reset();
        onClose();
      }}
      size="sm"
      title="Add technician"
      description="They sign in with this mobile number. A temporary password is created for you to give them."
      footer={
        <>
          <Button
            variant="secondary"
            onClick={() => {
              reset();
              onClose();
            }}
          >
            Cancel
          </Button>
          <Button type="submit" form="add-technician" loading={create.isPending}>
            Add technician
          </Button>
        </>
      }
    >
      <form id="add-technician" onSubmit={submit} noValidate className="space-y-4">
        <Input
          label="Name"
          value={name}
          onChange={(event) => setName(event.target.value)}
          error={errors['name']}
          autoComplete="off"
          required
          autoFocus
        />
        <Input
          label="Mobile number"
          type="tel"
          inputMode="numeric"
          placeholder="98765 43210"
          value={mobile}
          onChange={(event) => setMobile(event.target.value)}
          error={errors['mobile']}
          autoComplete="off"
          required
        />
        <Input
          label="Email (optional)"
          type="email"
          value={email}
          onChange={(event) => setEmail(event.target.value)}
          error={errors['email']}
          autoComplete="off"
        />
      </form>
    </Dialog>
  );
}

/* ---- Edit -------------------------------------------------------------- */

function EditTechnicianDialog({ technician, onClose }: { technician: User; onClose: () => void }) {
  const refresh = useRefreshCenter();
  const [name, setName] = useState(technician.name);
  const [email, setEmail] = useState(technician.email ?? '');
  const [errors, setErrors] = useState<Record<string, string>>({});

  const save = useMutation({
    mutationFn: () =>
      /* Email is sent even when blank — `""` is how the server is told to
         remove it (users.validation.ts). Leaving it out when empty was the
         bug: clearing the field and saving reported success but the old
         address never left the record. */
      api(`/users/${technician.id}`, {
        method: 'PATCH',
        body: { name: name.trim(), email: email.trim() },
      }),
    onSuccess: async () => {
      toast.success('Technician updated');
      onClose();
      await refresh();
    },
    onError: (error) => {
      if (error instanceof ApiError && error.issues.length > 0) {
        setErrors(Object.fromEntries(error.issues.map((issue) => [issue.field, issue.message])));
      } else {
        toast.error(errorMessage(error));
      }
    },
  });

  return (
    <Dialog
      open
      onClose={onClose}
      size="sm"
      title="Edit technician"
      description={`Mobile ${formatMobile(technician.mobile)} is their sign-in and cannot be changed here.`}
      footer={
        <>
          <Button variant="secondary" onClick={onClose}>
            Cancel
          </Button>
          <Button
            type="submit"
            form="edit-technician"
            loading={save.isPending}
            disabled={!name.trim()}
          >
            Save
          </Button>
        </>
      }
    >
      <form
        id="edit-technician"
        onSubmit={(event) => {
          event.preventDefault();
          save.mutate();
        }}
        noValidate
        className="space-y-4"
      >
        <Input
          label="Name"
          value={name}
          onChange={(event) => setName(event.target.value)}
          error={errors['name']}
          required
          autoFocus
        />
        <Input
          label="Email (optional)"
          type="email"
          value={email}
          onChange={(event) => setEmail(event.target.value)}
          error={errors['email']}
        />
      </form>
    </Dialog>
  );
}

/* ---- Activate / deactivate --------------------------------------------- */

function ToggleActiveDialog({
  technician,
  onClose,
  onStranded,
}: {
  technician: User;
  onClose: () => void;
  onStranded: (jobs: StrandedJob[]) => void;
}) {
  const refresh = useRefreshCenter();
  const deactivating = technician.isActive;

  const toggle = useMutation({
    mutationFn: () =>
      api<{ user: User; openJobsNeedingReassignment?: StrandedJob[] }>(`/users/${technician.id}`, {
        method: 'PATCH',
        body: { isActive: !deactivating },
      }),
    onSuccess: async (result) => {
      toast.success(deactivating ? `${technician.name} deactivated` : `${technician.name} can sign in again`);
      onClose();
      if (result.openJobsNeedingReassignment?.length) onStranded(result.openJobsNeedingReassignment);
      await refresh();
    },
    onError: (error) => toast.error(errorMessage(error)),
  });

  return (
    <Dialog
      open
      onClose={onClose}
      size="sm"
      title={deactivating ? `Deactivate ${technician.name}?` : `Activate ${technician.name}?`}
      description={
        deactivating
          ? 'They can no longer sign in or be given new jobs. Everything they have done stays on record.'
          : 'They can sign in again with their existing password, and can be assigned jobs.'
      }
      footer={
        <>
          <Button variant="secondary" onClick={onClose}>
            Cancel
          </Button>
          <Button
            variant={deactivating ? 'danger' : 'primary'}
            loading={toggle.isPending}
            onClick={() => toggle.mutate()}
          >
            {deactivating ? 'Deactivate' : 'Activate'}
          </Button>
        </>
      }
    >
      {deactivating && (technician.workload?.openJobs ?? 0) > 0 ? (
        <p className="rounded-lg bg-amber-50 px-3 py-2.5 text-sm text-amber-900">
          {technician.name} has {technician.workload?.openJobs} open{' '}
          {technician.workload?.openJobs === 1 ? 'job' : 'jobs'}. You will be shown them next, to reassign.
        </p>
      ) : (
        <p className="text-sm text-slate-600">You can change this again at any time.</p>
      )}
    </Dialog>
  );
}

/* ---- Reset password ---------------------------------------------------- */

function ResetPasswordDialog({
  technician,
  onClose,
  onIssued,
}: {
  technician: User;
  onClose: () => void;
  onIssued: (issued: IssuedPassword) => void;
}) {
  const refresh = useRefreshCenter();

  const reset = useMutation({
    mutationFn: () => api<IssuedPassword>(`/users/${technician.id}/reset-password`, { method: 'POST', body: {} }),
    onSuccess: async (result) => {
      onClose();
      onIssued(result);
      await refresh();
    },
    onError: (error) => toast.error(errorMessage(error)),
  });

  return (
    <Dialog
      open
      onClose={onClose}
      size="sm"
      title={`Reset password for ${technician.name}?`}
      description="Use this when they have forgotten it. They are signed out everywhere and choose a new password the next time they sign in."
      footer={
        <>
          <Button variant="secondary" onClick={onClose}>
            Cancel
          </Button>
          <Button loading={reset.isPending} onClick={() => reset.mutate()}>
            Reset password
          </Button>
        </>
      }
    >
      <p className="text-sm text-slate-600">A new temporary password will be shown once, for you to give them.</p>
    </Dialog>
  );
}
