/**
 * Report and dashboard routes (spec sections 5.1, 9, 16).
 *
 * One route per report, with `?format=json|csv|xlsx`. Keeping the export on
 * the same route as the report is deliberate: a separate `/export` endpoint
 * would be a second code path that could drift, and then the spreadsheet would
 * quietly disagree with the screen it was downloaded from.
 */
import { Router } from 'express';
import type { NextFunction, Request, RequestHandler, Response } from 'express';
import { sweepBreaches } from '../../core/sla.js';
import { forbidden, notFound } from '../../http/errors.js';
import { authenticate, requireAuth } from '../../middleware/authenticate.js';
import { requirePasswordChanged } from '../../middleware/authorize.js';
import type { AuthContext } from '../../middleware/authenticate.js';
import { dashboard } from './dashboard.service.js';
import { exportFilename, toCsv, toXlsx, type ExportInput } from './export.service.js';
import { describeFilters, ignoredFilters } from './report.filters.js';
import { formatDateTime } from './report.labels.js';
import type { ReportResult } from './report.types.js';
import * as reports from './reports.service.js';
import {
  REPORT_KINDS,
  dashboardQuerySchema,
  reportQuerySchema,
  type ReportFilterInput,
  type ReportKind,
} from './reports.validation.js';

function handler(
  fn: (req: Request, res: Response) => Promise<void>,
): RequestHandler {
  return (req, res, next: NextFunction) => {
    fn(req, res).catch(next);
  };
}

type ReportRunner = (filter: ReportFilterInput, auth: AuthContext) => Promise<ReportResult>;

const RUNNERS: Record<ReportKind, ReportRunner> = {
  complaints: reports.complaintReport,
  'service-centers': reports.serviceCenterReport,
  technicians: reports.technicianReport,
  products: reports.productReport,
  parts: reports.partsReport,
};

const isReportKind = (value: string): value is ReportKind =>
  (REPORT_KINDS as readonly string[]).includes(value);

const getReport = handler(async (req, res) => {
  const auth = requireAuth(req);

  /* Section 3.3 gives a technician no reporting at all — they have a work
     queue, not a management view. */
  if (auth.role === 'TECHNICIAN') {
    throw forbidden('Reports are for Admin and Service Center Owners');
  }

  const kind = String(req.params['kind']);
  if (!isReportKind(kind)) {
    throw notFound(`No report called '${kind}'. Available: ${REPORT_KINDS.join(', ')}`);
  }

  const { format, limit, ...filter } = reportQuerySchema.parse(req.query);

  /* Breaches are recorded before anything is counted (see core/sla.ts). */
  await sweepBreaches();
  const [result, filters] = await Promise.all([
    RUNNERS[kind](filter, auth),
    describeFilters(kind, filter, auth),
  ]);
  const ignored = ignoredFilters(kind, filter);

  /* Cap every table; an unbounded export is how a reporting endpoint takes a
     server down. `total` keeps the real count, so a cut table says so. */
  const tables = result.tables.map((table) => {
    const rows = table.rows.slice(0, limit);
    const total = Math.max(table.total, table.rows.length);
    return { ...table, rows, total, ...(rows.length < total ? { truncated: true } : {}) };
  });

  if (format === 'json') {
    res.status(200).json({
      kind,
      ...result,
      tables,
      filters,
      ignoredFilters: ignored,
      generatedAt: new Date(),
    });
    return;
  }

  const cut = tables.filter((table) => table.truncated);
  const payload: ExportInput = {
    title: result.title,
    meta: [
      { label: 'Generated', value: formatDateTime(new Date()) },
      { label: 'Generated by', value: auth.name },
      { label: 'Counts', value: result.dateBasis },
      ...filters,
      ...(ignored.length > 0
        ? [{ label: 'Not used by this report', value: ignored.map((f) => f.label).join(', ') }]
        : []),
      ...(cut.length > 0
        ? [{ label: 'Note', value: `${cut.map((t) => t.title).join(', ')} cut to the first ${limit} rows` }]
        : []),
    ],
    summary: result.summary,
    breakdowns: result.breakdowns,
    ...(result.trend ? { trend: result.trend } : {}),
    tables,
  };

  if (format === 'csv') {
    const filename = exportFilename(result.title, 'csv');
    res.setHeader('Content-Type', 'text/csv; charset=utf-8');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    /* A BOM, so Excel opens UTF-8 correctly rather than mangling any
       non-ASCII customer name. */
    res.status(200).send(`﻿${toCsv(payload)}`);
    return;
  }

  const buffer = await toXlsx(payload);
  const filename = exportFilename(result.title, 'xlsx');
  res.setHeader(
    'Content-Type',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  );
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
  res.setHeader('Content-Length', String(buffer.byteLength));
  res.status(200).end(buffer);
});

const getDashboard = handler(async (req, res) => {
  const auth = requireAuth(req);
  const query = dashboardQuerySchema.parse(req.query);
  await sweepBreaches();
  res.status(200).json(await dashboard(query, auth));
});

export const reportsRouter = Router();

reportsRouter.use(authenticate, requirePasswordChanged);

/* Sections 5.1 and 9. Scope decides which of the two it is. */
reportsRouter.get('/dashboard', getDashboard);

/* Section 16. `kind` is matched against a fixed table, never used to build a
   query — a report name is not a place to accept arbitrary input. */
reportsRouter.get('/reports/:kind', getReport);
